DROP TABLE `announcementRecipients`;--> statement-breakpoint
DROP TABLE `announcements`;--> statement-breakpoint
DROP TABLE `botConfig`;--> statement-breakpoint
DROP TABLE `eventTypes`;--> statement-breakpoint
DROP TABLE `gotAttacks`;--> statement-breakpoint
DROP TABLE `gotStrategies`;--> statement-breakpoint
DROP TABLE `gvgAttacks`;--> statement-breakpoint
DROP TABLE `gvgMatchInfo`;--> statement-breakpoint
DROP TABLE `gvgSeasons`;--> statement-breakpoint
DROP TABLE `members`;--> statement-breakpoint
DROP TABLE `nonAttackerAlerts`;--> statement-breakpoint
DROP TABLE `performanceRecords`;--> statement-breakpoint
DROP TABLE `reliquiasBossProgress`;--> statement-breakpoint
DROP TABLE `reliquiasDamage`;--> statement-breakpoint
DROP TABLE `reliquiasMemberAssignments`;--> statement-breakpoint
DROP TABLE `reliquiasMemberRoles`;--> statement-breakpoint
DROP TABLE `reliquiasSeasons`;--> statement-breakpoint
DROP TABLE `scheduleEntries`;--> statement-breakpoint
DROP TABLE `schedules`;--> statement-breakpoint
DROP TABLE `screenshotUploads`;--> statement-breakpoint
DROP TABLE `subAdmins`;--> statement-breakpoint
ALTER TABLE `users` MODIFY COLUMN `role` enum('user','admin') NOT NULL DEFAULT 'user';